# Natural Language Processing (NLP)

## CountVectorizer 
--> To convert text into number

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
text = ['Hello my name is james','james this is my python notebook','james trying to create a big dataset','james of words to try differnt','features of count vectorizer']

In [3]:
count_vect = CountVectorizer()

In [4]:
count_matrix = count_vect.fit_transform(text)

In [5]:
count_array = count_matrix.toarray()

In [6]:
df = pd.DataFrame(data=count_array,columns = count_vect.get_feature_names_out())

In [7]:
df

,big,count,create,dataset,differnt,features,hello,is,james,my,name,notebook,of,python,this,to,try,trying,vectorizer,words
0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,1,1,0,1,0,1,1,0,0,0,0,0
2,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0
3,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,1
4,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0

## Parameter
- Lowercase

--> Convert all characters to lowercase before tokenizing . Default is set to true and takes boolean value.

In [8]:
text = ['hello my name is james','Hello my name is James']

In [10]:
count_vect = CountVectorizer(lowercase=False)

In [11]:
count_matrix = count_vect.fit_transform(text)

In [12]:
count_array = count_matrix.toarray()

In [13]:
df = pd.DataFrame(data=count_array,columns = count_vect.get_feature_names_out())

In [14]:
df

   Hello  James  hello  is  james  my  name
0      0      0      1   1      1   1     1
1      1      1      0   1      0   1     1

- Stop_words

In [15]:
text = ['Hello my name is james','james this is my python notebook','james trying to create a big dataset','james of words to try differnt','features of count vectorizer']

In [16]:
count_vect = CountVectorizer(stop_words= ['is','to','my'])
count_matrix = count_vect.fit_transform(text)

In [17]:
count_array = count_matrix.toarray()

In [18]:
df = pd.DataFrame(data=count_array,columns = count_vect.get_feature_names_out())

In [19]:
df

,big,count,create,dataset,differnt,features,hello,james,name,notebook,of,python,this,try,trying,vectorizer,words
0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0
2,1,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0
3,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1
4,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0

- stop_words = Whole english language (helping verb like 370 words)

In [20]:
count_vect = CountVectorizer(stop_words= 'english')
count_matrix = count_vect.fit_transform(text)
count_array = count_matrix.toarray()
df = pd.DataFrame(data=count_array,columns = count_vect.get_feature_names_out())
df

,big,count,create,dataset,differnt,features,hello,james,notebook,python,try,trying,vectorizer,words
0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,1,1,0,0,0,0
2,1,0,1,1,0,0,0,1,0,0,0,1,0,0
3,0,0,0,0,1,0,0,1,0,0,1,0,0,1
4,0,1,0,0,0,1,0,0,0,0,0,0,1,0

## Using max_df and min_df(covered later)

- Max_df:

In [24]:
count_vect = CountVectorizer(max_df=1)
count_matrix = count_vect.fit_transform(text)
count_array = count_matrix.toarray()
df = pd.DataFrame(data=count_array,columns = count_vect.get_feature_names_out())
df

,big,count,create,dataset,differnt,features,hello,name,notebook,python,this,try,trying,vectorizer,words
0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0
2,1,0,1,1,0,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
4,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0

In [27]:
count_vect = CountVectorizer(max_df=0.75)
count_matrix = count_vect.fit_transform(text)
count_array = count_matrix.toarray()
df = pd.DataFrame(data=count_array,columns = count_vect.get_feature_names_out())
df
# Here 0.75 is 75% --> occuring the word

,big,count,create,dataset,differnt,features,hello,is,my,name,notebook,of,python,this,to,try,trying,vectorizer,words
0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,1,0,1,0,1,1,0,0,0,0,0
2,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
3,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,1,0,0,1
4,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0

- Min_df:

In [29]:
count_vect = CountVectorizer(min_df =2)
count_matrix = count_vect.fit_transform(text)
count_array = count_matrix.toarray()
df = pd.DataFrame(data=count_array,columns = count_vect.get_feature_names_out())
df

   is  james  my  of  to
0   1      1   1   0   0
1   1      1   1   0   0
2   0      1   0   0   1
3   0      1   0   1   1
4   0      0   0   1   0