In [1]:
import nltk
import pandas as pd

In [2]:
df=pd.read_csv("spam.csv",encoding="latin-1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [3]:
df.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis=1,inplace=True)

In [4]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.columns=["label","text"]

In [6]:
df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vipul\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [9]:
import nltk
import string
import re
stopwords=nltk.corpus.stopwords.words("english")

In [10]:
def clean_text(text):
    text="".join([char.lower() for char in text if char not in string.punctuation])
    tokens=re.split("\W+",text)
    text=[word for word in tokens if word not in stopwords]
    return text

In [13]:
x="Nah I don't think he goes to usf, he lives aro?"
x="".join([char.lower() for char in x if char not in string.punctuation])
x

'nah i dont think he goes to usf he lives aro'

In [14]:
tokens=re.split("\W+",x)

In [15]:
tokens

['nah', 'i', 'dont', 'think', 'he', 'goes', 'to', 'usf', 'he', 'lives', 'aro']

In [16]:
clean_text("Nah I don't think he goes to usf, he lives aro?")

['nah', 'dont', 'think', 'goes', 'usf', 'lives', 'aro']

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(analyzer=clean_text)
X_count=count_vect.fit_transform(df["text"])
print(X_count.shape)
print(count_vect.get_feature_names_out())

(5572, 9395)
['' '0' '008704050406' ... 'ûïharry' 'ûò' 'ûówell']

In [18]:
X_features=pd.DataFrame(X_count.toarray())
X_features.head()

,0,1,2,3,4,5,6,7,8,9,...,9385,9386,9387,9388,9389,9390,9391,9392,9393,9394
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X_features,df["label"],test_size=0.2)

In [22]:
rf=RandomForestClassifier()
rf_model=rf.fit(X_train,y_train)

In [23]:
y_pred=rf_model.predict(X_test)

In [24]:
from sklearn.metrics import classification_report

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.98       971
        spam       1.00      0.78      0.88       144

    accuracy                           0.97      1115
   macro avg       0.98      0.89      0.93      1115
weighted avg       0.97      0.97      0.97      1115

In [29]:
text=["I Kill You"]
count_vect1=count_vect.transform(text)
X_features=pd.DataFrame(count_vect1.toarray())
X_features.head()

,0,1,2,3,4,5,6,7,8,9,...,9385,9386,9387,9388,9389,9390,9391,9392,9393,9394
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
y_pred=rf_model.predict(count_vect1)

In [31]:
y_pred

array(['ham'], dtype=object)